
export const Theme = {
  colors: {
    primary: "text-amber-600",
    highlight: "text-amber-500",
    textMain: "text-stone-300",
    textMuted: "text-stone-500",
    border: "border-stone-800",
    borderHighlight: "border-amber-900/30",
    accent: "bg-amber-700",
    bgDark: "bg-stone-900",
    bgCard: "bg-[#1a1816]",
  },
  typography: {
    // Headings
    h1: "text-6xl md:text-4xl font-serif font-bold text-stone-100 mb-3 tracking-tight",
    h2: "text-3xl font-serif font-bold text-amber-500 tracking-widest",
    h3: "text-base font-bold uppercase tracking-widest text-amber-500",
    h4: "text-xl font-serif font-bold text-amber-600 tracking-wide",
    
    // Body Text
    body: "text-base font-serif text-stone-300 leading-relaxed",
    bodySm: "text-sm font-serif text-stone-400",
    bodyXs: "text-xs font-serif text-stone-500",
    
    // Monospace / Data
    monoXl: "text-2xl font-mono text-stone-200",
    monoLg: "text-xl font-mono text-stone-200",
    monoBase: "text-base font-mono text-amber-600",
    monoSm: "text-sm font-mono text-stone-400",
    monoXs: "text-xs font-mono text-stone-500",

    // Functional Labels
    label: "text-xs text-stone-500 uppercase tracking-widest font-sans",
    subtext: "text-xs text-stone-600 font-mono tracking-widest",
    caption: "text-xs text-stone-600 italic font-serif",
    
    // Special
    heroNumber: "text-5xl font-serif text-white",
    serifLg: "text-5xl font-serif text-amber-500 font-bold mb-2",
  },
  layout: {
    page: "min-h-screen bg-stone-950 text-stone-200 selection:bg-amber-900 selection:text-white flex flex-col",
    container: "max-w-7xl mx-auto px-4",
    main: "flex-1 overflow-y-auto",
    footer: "border-t border-stone-800 py-10 text-center text-stone-600 text-sm",
  },
  nav: {
    container: "border-b border-stone-800 bg-stone-900/50 backdrop-blur sticky top-0 z-50",
    inner: "max-w-7xl mx-auto px-4 h-18 flex items-center justify-between py-3",
    logoBox: "w-10 h-10 bg-amber-700 text-stone-900 flex items-center justify-center font-bold rounded shadow-lg shadow-amber-900/20 text-lg",
    logoText: "font-serif text-2xl tracking-wider font-bold text-stone-200 hidden sm:block",
    controlsContainer: "flex items-center gap-2 bg-stone-800 p-1.5 rounded-lg border border-stone-700 relative",
    controlButton: "p-2 hover:bg-stone-700 rounded text-stone-400 hover:text-amber-400 transition-colors",
    activeControlButton: "text-amber-500 bg-stone-700",
    dateInputWrapper: "relative group px-1",
    dateInput: "bg-transparent text-stone-200 font-mono text-base border-none outline-none focus:ring-1 focus:ring-amber-700/50 rounded px-2 py-1 [&::-webkit-calendar-picker-indicator]:hidden cursor-pointer hover:bg-stone-700/50 transition-colors",
    todayButton: "hidden sm:flex items-center gap-2 px-5 py-2 text-sm font-bold uppercase tracking-widest text-stone-500 hover:text-amber-500 transition-colors",
    tabContainer: "border-b border-stone-800 bg-stone-900",
    tabWrapper: "max-w-7xl mx-auto flex justify-center",
    tabButton: "px-8 py-4 flex items-center gap-3 text-base uppercase tracking-widest font-serif transition-all border-b-2",
    tabActive: "border-amber-600 text-amber-500 bg-stone-900",
    tabInactive: "border-transparent text-stone-500 hover:text-stone-300",
  },
  calendar: {
    popupWrapper: "absolute top-full mt-4 left-1/2 -translate-x-1/2 z-50",
    overlay: "fixed inset-0 z-40 bg-black/10",
    container: "bg-[#1c1917] border border-amber-900/60 rounded-md shadow-2xl p-4 w-72 font-serif text-stone-200 select-none",
    header: "flex justify-between items-center mb-4 pb-2 border-b border-stone-800 gap-1",
    navButton: "p-1 hover:text-amber-500 hover:bg-stone-800 rounded transition-colors shrink-0",
    titleContainer: "flex items-center justify-center gap-2 font-bold text-base tracking-widest text-amber-500 flex-1",
    inputGroup: "flex items-center group",
    yearInput: "w-14 bg-transparent text-right border-b border-transparent group-hover:border-stone-700 focus:border-amber-500 outline-none appearance-none m-0 p-0 hover:text-amber-400 focus:text-amber-400 transition-colors",
    monthSelect: "bg-[#1c1917] text-right border-b border-transparent group-hover:border-stone-700 focus:border-amber-500 outline-none appearance-none cursor-pointer pr-1 hover:text-amber-400 focus:text-amber-400 transition-colors",
    gridHeader: "grid grid-cols-7 gap-1 text-center mb-2",
    grid: "grid grid-cols-7 gap-1",
    dayCell: "h-8 w-8 rounded-full flex items-center justify-center text-sm transition-all",
    dayCellInactive: "opacity-30 text-stone-500",
    dayCellSelected: "bg-amber-700 text-white font-bold shadow-lg shadow-amber-900/50 scale-110 z-10",
    dayCellToday: "border border-amber-700/50 text-amber-500",
    dayCellHover: "hover:bg-stone-800 hover:text-amber-400",
    footer: "mt-4 pt-2 border-t border-stone-800 flex justify-between items-center text-xs",
    footerButton: "text-stone-500 hover:text-stone-300 px-2 py-1",
    footerAction: "text-amber-600 hover:text-amber-400 font-bold px-2 py-1",
  },
  bazi: {
    container: "border border-stone-800 rounded bg-[#1c1917] overflow-hidden shadow-lg",
    grid: "grid grid-cols-4",
    column: "flex flex-col border-r border-stone-800 last:border-0",
    columnDay: "bg-stone-800/20",
    header: "p-3 text-center border-b border-stone-800 bg-stone-900/40",
    headerTitle: "text-xs text-stone-500 uppercase tracking-widest block mb-1",
    headerValue: "text-sm font-bold text-amber-700",
    shiShenBox: "p-2 text-center h-10 flex items-center justify-center border-b border-stone-800/50",
    mainCharBox: "p-4 text-center border-b border-stone-800",
    ganText: "text-2xl font-serif font-bold",
    ganTextDay: "text-amber-500",
    ganTextNormal: "text-stone-300",
    zhiText: "text-2xl font-serif font-bold text-stone-300",
    subText: "text-[10px] block mt-1 text-stone-600 font-mono",
    hiddenStemsBox: "flex-1 p-3 text-center border-b border-stone-800/50 bg-stone-900/20",
    hiddenStemRow: "flex justify-between items-center text-xs",
    footer: "bg-stone-900/50 p-4 border-t border-stone-800 flex justify-between items-center text-xs text-stone-400",
  },
  astro: {
    container: "max-w-4xl mx-auto p-1 bg-[#1c1917] border-2 border-amber-800/40 rounded-sm shadow-2xl",
    header: "bg-[#2c241b] p-8 text-center border-b-4 border-amber-900 relative overflow-hidden",
    headerStamp: "absolute top-3 left-3 text-xs text-amber-900/40 border border-amber-900/40 p-1.5 font-serif writing-vertical-rl",
    headerIcon: "text-amber-500/20 absolute -right-8 -top-8",
    headerTitle: "text-3xl md:text-4xl font-serif text-amber-500 font-bold tracking-widest mb-2",
    headerSubtitle: "text-stone-500 text-sm uppercase tracking-[0.2em] mb-5",
    headerDate: "inline-block bg-amber-900/20 px-6 py-1.5 rounded-full border border-amber-900/40 text-amber-600 text-sm font-mono",
    content: "p-8 md:p-12 bg-[#161412] text-stone-300 font-serif leading-relaxed",
    section: "mb-8 border-b-2 border-amber-900/30 pb-6 last:border-0",
    sectionTitle: "text-amber-600 font-serif font-bold uppercase tracking-widest text-base mb-4 flex items-center gap-3",
    dataField: "flex justify-between items-center py-1.5",
    dataLabel: "text-stone-500 font-serif text-sm",
    dataValue: "font-mono text-base",
    highlightValue: "text-amber-500 font-bold",
    normalValue: "text-stone-300",
    alertBox: "bg-red-900/10 border border-red-900/30 p-5 rounded",
    alertTitle: "flex items-center gap-3 text-red-500 font-bold mb-4 text-base",
    alertFooter: "mt-4 pt-4 border-t border-red-900/20",
    infoBox: "flex items-start gap-5 mb-5 bg-stone-900/50 p-5 rounded border border-stone-800",
    planetRow: "flex justify-between items-center p-3 hover:bg-stone-800/50 rounded transition-colors border-b border-stone-800/50 last:border-0",
    conclusionBox: "bg-[#241f1b] p-8 border-l-4 border-amber-700 text-base leading-8 text-stone-300 font-serif italic",
    footer: "bg-[#2c241b] p-6 text-center border-t border-amber-900/30",
  },
  dayan: {
    card: "bg-[#1a1816] border border-amber-900/20 p-6 rounded-sm relative overflow-hidden group hover:border-amber-900/40 transition-colors",
    headerIcon: "text-amber-600 scale-110",
    headerTitle: "text-base font-bold uppercase tracking-widest text-amber-500",
    headerSubtitle: "text-xs text-stone-500 font-serif italic mt-0.5",
    valueBox: "bg-stone-900/40 rounded border border-stone-800/50 text-center p-3",
    sectionHeader: "flex items-center gap-3 mb-5 border-b border-amber-900/20 pb-3",
    dataRow: "flex justify-between items-center py-2 border-b border-stone-800/50 last:border-0",
    progressBarTrack: "w-full h-1.5 bg-stone-800 rounded-full overflow-hidden",
    progressBarFill: "h-full bg-amber-700 transition-all duration-500",
    badge: "px-2 py-0.5 bg-amber-900/40 text-amber-500 text-xs rounded font-bold uppercase tracking-wider border border-amber-900/50",
    interpretationBox: "bg-[#1c1917]/80 p-4 border-l-2 border-amber-600 mb-5 shadow-inner backdrop-blur-sm relative z-10",
    mathDisplay: "flex flex-col border-l-2 border-amber-900/30 pl-4",
    bgPanel: "bg-[#1a1816]",
    bgDark: "bg-stone-900",
    bgDarker: "bg-stone-950",
    bgTranslucent: "bg-stone-900/40",
  },
  hexagram: {
    container: "flex flex-col justify-between items-center",
    lineWrapper: "w-full h-[12%] flex justify-between transition-all duration-300",
    solidLine: "w-full h-full rounded-sm transition-all duration-300",
    brokenLinePart: "w-[42%] h-full rounded-sm transition-all duration-300",
    brokenLineSpacer: "w-[16%]"
  }
};
